### ISSUE TITLE
Remove unused or duplicated code

### ISSUE THREAD

**Issue by BennyCarlsson** [lingonsaft/hacktoberfest#947]
A lot of code in this project is now duplicated or unused. It needs to be located and removed.
Make sure the code is really not used and that you don't break anything ;)

**Comment by dushivani** [comment]
I would like to give this a try.

**Comment by CQW-Code** [comment]
I'd like to give this a go.

**Comment by henriquenasc** [comment]
Hello @CQW-Code ! In case you have to run a local server for the site to appear completely complete. This is because some things are loaded dynamically.

I for example rode on the server built into php with "php -S localhost: 8080". But there are several simple and legal local servers in various languages: D.

**Comment by CQW-Code** [comment]
I can do local servers for React & Ruby & Rails lol but I don't think I've done one for HTML/CSS!  Time to google...

**Comment by BennyCarlsson** [comment]
Will make an issue for the menu not working locally :)

**Comment by richie-south** [comment]
The menu should work locally now :)

**Comment by richie-south** [comment]
Closing this issue for now, If you have started working on this don't be afraid to submit an pull request 😉
